### ISSUE TITLE
Could not load library libvx_tidl_rt.so

### ISSUE THREAD

**Issue by AJOSHI35** [TexasInstruments/edgeai-tidl-tools#15]
When try to execute `python3 tflr_delegate.py -c` from /examples/osrt_python/tfl , the following error is observed

Running 3 Models - ['cl-tfl-mobilenet_v1_1.0_224', 'ss-tfl-deeplabv3_mnv2_ade20k_float', 'od-tfl-ssd_mobilenet_v2_300_float']
Running_Model :  cl-tfl-mobilenet_v1_1.0_224
Running_Model :  ss-tfl-deeplabv3_mnv2_ade20k_float
Running_Model :  od-tfl-ssd_mobilenet_v2_300_float
Process Process-2:
Process Process-1:
Traceback (most recent call last):
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
Traceback (most recent call last):
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
Process Process-3:
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError: could not load library libvx_tidl_rt.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
ValueError: could not load library libvx_tidl_rt.so
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)

During handling of the above exception, another exception occurred:

  File "tflrt_delegate.py", line 157, in run_model
    experimental_delegates=[tflite.load_delegate(os.path.join(tidl_tools_path, 'tidl_model_import_tflite.so'), delegate_options)])
Traceback (most recent call last):
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 155, in load_delegate
    library, str(e)))
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
ValueError: Failed to load delegate from /home/treerunner/Documents/SDK/7_03_00/TI_RTOS_PSDK/ti-processor-sdk-rtos-j721e-evm-07_03_00_07/tidl_j7_02_00_00_07/tidl_tools/tidl_model_import_tflite.so
could not load library libvx_tidl_rt.so
  File "tflrt_delegate.py", line 157, in run_model
    experimental_delegates=[tflite.load_delegate(os.path.join(tidl_tools_path, 'tidl_model_import_tflite.so'), delegate_options)])
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 155, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from /home/treerunner/Documents/SDK/7_03_00/TI_RTOS_PSDK/ti-processor-sdk-rtos-j721e-evm-07_03_00_07/tidl_j7_02_00_00_07/tidl_tools/tidl_model_import_tflite.so
could not load library libvx_tidl_rt.so
Traceback (most recent call last):
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError: could not load library libvx_tidl_rt.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "tflrt_delegate.py", line 157, in run_model
    experimental_delegates=[tflite.load_delegate(os.path.join(tidl_tools_path, 'tidl_model_import_tflite.so'), delegate_options)])
  File "/home/treerunner/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 155, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from /home/treerunner/Documents/SDK/7_03_00/TI_RTOS_PSDK/ti-processor-sdk-rtos-j721e-evm-07_03_00_07/tidl_j7_02_00_00_07/tidl_tools/tidl_model_import_tflite.so
could not load library libvx_tidl_rt.so

Note: In ${PSDK_RTOS_PATH}/ti_dl/rt/out/PC/x86_64/LINUX/release i can find the libvx_tidl_rt.so library. I wonder if i missed a makefile target that installs these libraries into the correct location. Any help on this would be great

**Comment by kumardesappan** [comment]
@AJOSHI35 The edge-tidl-tools repo is supported from SDK version 8.0 onwards, for earlier versions please follow the documentation available in SDK itself.
