### ISSUE TITLE
Is there a tutorial on how to deploy yolo?

### ISSUE THREAD

**Issue by Ghustwb** [TexasInstruments/edgeai-tidl-tools#26]
I want to deploy my custom model based on YOLOX to TDA4, I do not know how to generate artifatcts

**Comment by kumardesappan** [comment]
Please refer below for creating onnx model for yolox
https://github.com/TexasInstruments/edgeai-yolox

And then follow the documentation below to compile and run the same model
https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/examples/osrt_python/README.md

you can also refer to below Webinar for more details
https://training.ti.com/process-efficient-object-detection-using-yolov5-and-tda4x-processors

**Comment by dpetersonVT23** [comment]
When I run onnxrt_ep.py in osrt_python I get the following error, how do I fix this? Why is TIDL not available?
I am trying to compile my YOLOv5 Ti Lite ONNX and PROTOTXT for use on the Beaglebone AI.

Available execution providers :  ['CPUExecutionProvider']

Running 1 Models - ['yolov5s6_640_ti_lite']

Running_Model :  yolov5s6_640_ti_lite  

/home/mm282681/miniconda3/envs/tidl-tools/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:56: UserWarning: Specified provider 'TIDLExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  "Available providers: '{}'".format(name, ", ".join(available_provider_names)))
Process Process-1:
Traceback (most recent call last):
  File "/home/mm282681/miniconda3/envs/tidl-tools/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/mm282681/miniconda3/envs/tidl-tools/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "onnxrt_ep.py", line 190, in run_model
    sess = rt.InferenceSession(config['model_path'] ,providers=EP_list, provider_options=[delegate_options, {}], sess_options=so)
  File "/home/mm282681/miniconda3/envs/tidl-tools/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/mm282681/miniconda3/envs/tidl-tools/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 379, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: Unknown Provider Type: TIDLExecutionProvider
