### ISSUE TITLE
[ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: the graph is not acyclic.

### ISSUE THREAD

**Issue by aneesh1514** [TexasInstruments/edgeai-tidl-tools#38]
I am trying to compile the mobilenet-SSD based model on onnxruntime. But I am facing an error.

Preliminary subgraphs created = 2
Final number of subgraphs created are : 1, - Offloaded Nodes - 48, Total Nodes - 55
Node in deny list...delegated to ARM --- layer type - Transpose, Node name - Transpose_45
Node in deny list...delegated to ARM --- layer type - Reshape, Node name - Reshape_46
Node in deny list...delegated to ARM --- layer type - Transpose, Node name - Transpose_50
Node in deny list...delegated to ARM --- layer type - Reshape, Node name - Reshape_51
Node in deny list...delegated to ARM --- layer type - Concat, Node name - Concat_52
Node in deny list...delegated to ARM --- layer type - Concat, Node name - Concat_53
Node in deny list...delegated to ARM --- layer type - Softmax, Node name - Softmax_54
Running runtimes graphviz - /data/home/paneesh/edgeai-tidl-tools/tidl_tools/tidl_graphVisualiser_runtimes.out ../../../model-artifacts//fd//allowedNode.txt ../../../model-artifacts//harman-fd//tempDir/graphvizInfo.txt ../../../model-artifacts//harman-fd//tempDir/runtimes_visualization.svg
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "onnxrt_ep.py", line 174, in run_model
    sess = rt.InferenceSession(config['model_path'] ,providers=EP_list, provider_options=[delegate_options, {}], sess_options=so)
  File "/data/home/paneesh/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options)
  File "/data/home/paneesh/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 315, in _create_inference_session
    sess.initialize_session(providers, provider_options)
**onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: the graph is not acyclic.**

The onnx model is converted from a PyTorch model.

**But the model is working with the CPU.(CPUEXECUTIONPROVIDER).**

Please help me in solving the issue.

**Comment by mash2612** [comment]
@aneesh1514  were you able to resolve this issue?

**Comment by aneesh1514** [comment]
No, Still we are not able to solve this issue.
