### ISSUE TITLE
models compiled on ubuntu 22.04 does not execured  on the board (tda4vm)

### ISSUE THREAD

**Issue by smzahraee** [TexasInstruments/edgeai-tidl-tools#84]
I compiled the model on x86 using ubuntu 22.04 then copied models and model_artifacts to the board and run the infer but I get following errors 

```
root@tda4vm-sk:/opt/edgeai-tidl-tools/examples/osrt_python/tfl# python3 tflrt_delegate.py -d
Running 4 Models - ['cl-tfl-mobilenet_v1_1.0_224', 'ss-tfl-deeplabv3_mnv2_ade20k_float', 'od-tfl-ssd_mobilenet_v2_300_float', 'od-tfl-ssdlite_mobiledet_dsp_320x320_coco']


Running_Model :  cl-tfl-mobilenet_v1_1.0_224

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/edgeai-tidl-tools/examples/osrt_python/tfl/tflrt_delegate.py", line 282, in <module>
    run_model(model, mIdx)
  File "/opt/edgeai-tidl-tools/examples/osrt_python/tfl/tflrt_delegate.py", line 180, in run_model
    interpreter = tflite.Interpreter(model_path=config['model_path'], num_threads=2)
  File "/usr/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 449, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/edgeai-tidl-tools/examples/osrt_python/tfl/tflrt_delegate.py", line 282, in <module>
    run_model(model, mIdx)
  File "/opt/edgeai-tidl-tools/examples/osrt_python/tfl/tflrt_delegate.py", line 180, in run_model
    interpreter = tflite.Interpreter(model_path=config['model_path'], num_threads=2)
  File "/usr/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 449, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
SystemError: <built-in method CreateWrapperFromFile of PyCapsule object at 0xffffb112c7e0> returned a result with an exception set
root@tda4vm-sk:/opt/edgeai-tidl-tools/examples/osrt_python/tfl# python3 tflrt_delegate.py -x
usage: tflrt_delegate.py [-h] [-c] [-d] [-z] [-m MODELS]
tflrt_delegate.py: error: unrecognized arguments: -x

```

**Comment by vtrip97** [comment]
@smzahraee - Can you ensure the tidl-tools version is compatible with the SDK version you're using on your board? Refer to the following [Version Compatibility Table](https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/docs/version_compatibility_table.md)
